server.port=8080


spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/9awi_niveau?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


jwt.secret=mySuperSecretKey12345678901234567890ExtraLongSecretKeyForHS512Authentication2025
jwt.expiration=86400000

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=428009874445-uirq408arbih2pstc2225h67faophn0j.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# Email Configuration
brevo.api.key=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
brevo.sender.email=aminekilani901@gmail.com
brevo.sender.name=9awi Niveau
app.frontend.url=http://localhost:4200

# Image Upload Configuration
upload.dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# AI Chatbot Configuration
ai.api.key=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
ai.api.url=https://openrouter.ai/api/v1/chat/completions
ai.model=meta-llama/llama-3.2-3b-instruct:free
